### ISSUE TITLE
TypeError: this.auth.authz is null

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#468]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-frontend/issues/4542/

```
TypeError: this.auth.authz is null
  at this (./src/app/shared/keycloak.service.ts:97:12)
  at view (./src/app/wizard/services/app-launcher-token.service.ts:51:12)
...
(45 additional frame(s) were not displayed)
```

**Comment by ia3andy** [comment]
Duplicate https://github.com/fabric8-launcher/launcher-frontend/issues/542
