### ISSUE TITLE
Get rid of some annoying warnings in the JS console

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#480]
```
Injected settings are undefined
long-stack-trace-zone.js?fcc3:149 >>>>>>  Error: STACKTRACE TRACKING
long-stack-trace-zone.js?fcc3:149 >>>>>>     at __SEP_TAG__ (eval at <anonymous> (http://localhost:8088/polyfills.js:3148:1), <anonymous>:128:37) [<root>]     at captureStackTraces (eval at <anonymous> (http://localhost:8088/polyfills.js:3148:1), <anonymous>:128:37) [<root>]
```
```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
<!-- inject options list template -->
[WARNING ->]<template [ngTemplateOutlet]="optionsListTemplate || (isBs4 ? bs4Template : bs3Template)"
  [ngOutlet"): ng:///TypeaheadModule/TypeaheadContainerComponent.html@2:0
```

**Comment by ia3andy** [comment]
closed by #518
