### ISSUE TITLE
Error: Uncaught (in promise): [object Undefined]

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#545]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-frontend/issues/6115/

```
Error: Uncaught (in promise): [object Undefined]
  at P (/launch/polyfills.878fde0883bfdcc19830.bundle.js:1:13825)
  at P (/launch/polyfills.878fde0883bfdcc19830.bundle.js:1:13383)
  at None (/launch/polyfills.878fde0883bfdcc19830.bundle.js:1:14613)
  at e.invokeTask (/launch/polyfills.878fde0883bfdcc19830.bundle.js:1:8841)
  at Object.onInvokeTask (/launch/main.6de6a779ea41c539e3cd.bundle.js:1:490272)
...
(45 additional frame(s) were not displayed)
```

**Comment by edewit** [comment]
reverted that change 18b5ff6c695aa848617f707380cf06ec3b2dffb7
