### ISSUE TITLE
TypeError: this.auth.authz.login is not a function. (In 'this.auth.authz.login({redirectUri:e})', 'this.auth...

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#655]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-frontend/issues/6359/

```
TypeError: this.auth.authz.login is not a function. (In 'this.auth.authz.login({redirectUri:e})', 'this.auth.authz.login' is undefined)
  at handleEvent (./src/app/shared/keycloak.service.ts:79:21)
  at dispatchEvent (./node_modules/@angular/core/fesm5/core.js:7718:1)
  at apply (./node_modules/@angular/platform-browser/fesm5/platform-browser.js:995:1)
  at wrapped (./node_modules/raven-js/src/raven.js:377:1)
  at invokeTask (./node_modules/@angular/core/fesm5/core.js:3816:1)
...
(4 additional frame(s) were not displayed)
```

**Comment by ia3andy** [comment]
Closed by #658
