### ISSUE TITLE
TypeError: a is null in project-progress-createapp-nextstep.component.js

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#663]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-frontend/issues/7060/

```
TypeError: a is null
  at listener (./node_modules/ngx-launcher/src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.js:36:59)
  at func (./node_modules/zone.js/dist/zone.js:1188:1)
  at wrapped (./node_modules/raven-js/src/raven.js:377:1)
  at delegate (./node_modules/zone.js/dist/zone.js:421:1)
  at this (./node_modules/@angular/core/fesm5/core.js:3816:1)
...
(5 additional frame(s) were not displayed)
```

**Comment by ia3andy** [comment]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-frontend/issues/7096/
